export default function getAllProducts() {
  return [
    {
      id: "0001",
      slug: "new-balance-550-pink-white-womens",
      name: "New Balance 550 Pink White",
      category: "Women's",
      price: 750_000,
      stock: 100,
      imageUrl: "https://d5ibtax54de3q.cloudfront.net/eyJidWNrZXQiOiJraWNrYXZlbnVlLWFzc2V0cyIsImtleSI6InByb2R1Y3RzLzY4MjAyLzFkMDNkMDhmMjMyNjliZTNlZGU4Mjk0OTA5NWFlYjE1LnBuZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6MTQwMH19fQ==",
      description: `Embracing a minimalistic approach, this iteration of the 550 showcases a sleek color blocking scheme. Crafted with a combination of leather and mesh materials, the shoe ensures breathability through strategically placed perforations. A pristine White foundation serves as the backdrop, elegantly complemented by vibrant Pink accents. These contrasting elements adorn the tongue trim, padded “N” side logos, embroidered “NB” heel logos, ankle overlay, heel counter, and a portion of the rubber outsole. To further enhance the design, the lateral side features “550” text, while the signature New Balance branding appears on woven labels and insoles. The ensemble is completed by a White EVA midsole, providing comfort and support.`,
    },
    {
      id: "0002",
      slug: "new-balance-530-silver-cream-mens",
      name: "New Balance 530 Silver Cream",
      category: "Men's",
      price: 1_510_000,
      stock: 110,
      imageUrl: "https://d5ibtax54de3q.cloudfront.net/eyJidWNrZXQiOiJraWNrYXZlbnVlLWFzc2V0cyIsImtleSI6InByb2R1Y3RzLzM3MjUwL2I4ZTYzYTA3ZTIxYzZjZmUzOGUyZTMyZjk4OGMxZjg3LnBuZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6MTQwMH19fQ==",
      description: `The New Balance 530 sneaker is a retro-inspired shoe featuring a sleek and versatile design. Constructed with a combination of synthetic and mesh materials, it ensures breathability and durability. The shoe showcases a classic color palette with silver and cream tones, making it a stylish choice for any occasion. Equipped with advanced cushioning and support, the New Balance 530 provides comfort for all-day wear, perfect for those who appreciate both fashion and function.`,
    },
    {
      id: "0003",
      slug: "new-balance-408-raincloud-grey-mens",
      name: "New Balance 408 Raincloud Grey",
      category: "Men's",
      price: 520_000,
      stock: 70,
      imageUrl: "https://d5ibtax54de3q.cloudfront.net/eyJidWNrZXQiOiJraWNrYXZlbnVlLWFzc2V0cyIsImtleSI6InByb2R1Y3RzLzcyOTk3LzdjMzgyNzc0ODNmZGExMmU0ZWVjZWQ0YmI3YjdhOTZkLnBuZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6MTQwMH19fQ==",
      description: `The New Balance 408 Raincloud Grey offers a sleek design with a comfortable fit. This men's sneaker features a versatile grey color scheme with a combination of durable materials. Ideal for both casual and athletic wear, it provides excellent support and cushioning for all-day comfort.`,
    },
    {
      id: "0004",
      slug: "new-balance-550-lilac-womens",
      name: "New Balance 550 Lilac",
      category: "Women's",
      price: 700_000,
      stock: 120,
      imageUrl: "https://d5ibtax54de3q.cloudfront.net/eyJidWNrZXQiOiJraWNrYXZlbnVlLWFzc2V0cyIsImtleSI6InByb2R1Y3RzLzY4MTk4L2FhZmRhMTdkMjA5MTM4NjYxNWEwYmQ4Y2UwNmY1Y2I4LnBuZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6MTQwMH19fQ==",
      description: `The original 550 debuted in 1989 and made its mark on basketball courts from coast to coast. After its initial run, the 550 was filed away in the archives, before being reintroduced in limited-edition releases in late 2020, and returned to the full-time lineup in 2021, quickly becoming a global fashion favorite. The 550’s low top, streamlined silhouette offers a clean take on the heavy-duty designs of the late ‘80s, while the dependable leather, synthetic, and mesh upper construction is a classic look in any era.`,
    },
    {
      id: "0005",
      slug: "new-balance-550-white-nb-navy-mens",
      name: "New Balance 550 White NB Navy",
      category: "Men's",
      price: 900_000,
      stock: 0,
      imageUrl: "https://d5ibtax54de3q.cloudfront.net/eyJidWNrZXQiOiJraWNrYXZlbnVlLWFzc2V0cyIsImtleSI6InByb2R1Y3RzLzc5MjE3LzQ4NTc4N2JkMWVhNTAxNmQ4YTkwZWYxZDg2NWU3OGMxLnBuZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6MTQwMH19fQ==",
      description: `Will the popularity of the New Balance 550 continue to grow in 2024? Only time will tell but you can bet that New Balance will continue giving us new colorways of the model left and right. The latest offering of the retro hoops model takes on a clean aesthetic as the sneaker boasts a White perforated leather throughout the upper while Navy and Quarrel Blue serve as accent hues on the branding, ankles, overlays, and even the outsoles. For some added balance we have the addition of grey on the heels. `,
    },
    {
      id: "0006",
      slug: "new-balance-247-pink-womens",
      name: "New Balance 247 Pink",
      category: "Women's",
      price: 740_000,
      stock: 1000,
      imageUrl: "https://d5ibtax54de3q.cloudfront.net/eyJidWNrZXQiOiJraWNrYXZlbnVlLWFzc2V0cyIsImtleSI6InByb2R1Y3RzLzk5NjI0LzRkYWQyMmQ3ZThlZjRiZWEwOWY2NThiZjZlMzU3ODQ1LnBuZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6MTQwMH19fQ==",
      description: `The New Balance 247 Pink is a stylish and comfortable women's sneaker. The shoe features a pink color scheme with a combination of durable materials. It is perfect for casual wear and provides excellent support and cushioning for all-day comfort.`,
    },
    {
      id: "0007",
      slug: "new-balance-530-white-dark-arctic-mens",
      name: "New Balance 530 White Dark Arctic",
      category: "Men's",
      price: 1_420_000,
      stock: 10,
      imageUrl: "https://d5ibtax54de3q.cloudfront.net/eyJidWNrZXQiOiJraWNrYXZlbnVlLWFzc2V0cyIsImtleSI6InByb2R1Y3RzLzEwMzc0MS81MGZkOTE3YjE2YTMxMDFhNGFmZTliZmIwZDIwYjE3MS5wbmciLCJlZGl0cyI6eyJyZXNpemUiOnsid2lkdGgiOjE0MDB9fX0=",
      description: `The original MR530 combined turn of the millennium aesthetics with the reliability of a high milage running shoe. The reintroduced 530 applies a contemporary, everyday style outlook to this performance-minded design. A segmented ABZORB midsole is paired with a classic mesh and synthetic overlay upper design, which utilizes sweeping curves and angles for a distinctive, high-tech look.`,
    },
    {
      id: "0008",
      slug: "new-balance-857v3-white-cyclone-womens",
      name: "New Balance 857v3 White Cyclone",
      category: "Women's",
      price: 740_000,
      stock: 90,
      imageUrl: "https://d5ibtax54de3q.cloudfront.net/eyJidWNrZXQiOiJraWNrYXZlbnVlLWFzc2V0cyIsImtleSI6InByb2R1Y3RzLzk5Njk3LzVkYWJmODhhZTU0MjNhNTIwNjExMmIwMWFjOTAxODY0LnBuZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6MTQwMH19fQ==",
      description: `New Balance 857v3 White Cyclone is a stylish and comfortable women's running shoe. The shoe features a white color scheme with a combination of breathable mesh and synthetic materials. It is perfect for casual running and provides excellent support and cushioning for a comfortable ride.`,
    },
  ];
}

